### ISSUE TITLE
tag생성 시 enter 키를 누르지 않은 경우 대응

### ISSUE THREAD

**Issue by innerstella** [WhatToDo6/WhatToDo#134]
![image](https://github.com/WhatToDo6/WhatToDo/assets/77491430/486fc554-b593-4da3-b4d0-a2a58aad9ad7)

위와 같은 상황에서 o만 입력한 후 엔터 치지 않은 경우!

**Comment by innerstella** [comment]
제 의견은 엔터 키 누르지 않은 경우에는 태그를 생성하지 않도록 하는 게 어떨까 합니다!

노션 태그 생성 방식을 참고했습니다 👀 
![2024-04-253 45 24-ezgif com-video-to-gif-converter](https://github.com/WhatToDo6/WhatToDo/assets/77491430/040e9a9b-6524-423e-b550-f54d308b07e4)

**Comment by JaeBeen95** [comment]
좋은 생각입니다 :)

**Comment by JaeBeen95** [comment]
> 제 의견은 엔터 키 누르지 않은 경우에는 태그를 생성하지 않도록 하는 게 어떨까 합니다!
> 
> 노션 태그 생성 방식을 참고했습니다 👀 ![2024-04-253 45 24-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/77491430/325502379-040e9a9b-6524-423e-b550-f54d308b07e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzE1OTQsIm5iZiI6MTcxNDAzMTI5NCwicGF0aCI6Ii83NzQ5MTQzMC8zMjU1MDIzNzktMDQwZTlhOWItNjUyNC00MjNlLWI1NTAtZjU0ZDMwOGIwN2U0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODM2NDBiMDQyN2MyZDFmMDgyNGJjNmQ4Zjc3ZDNjYzgxNmQ5YTVkYjEzNTk0MGVmMTFhOTkxM2Y2NGYyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.230niwAJTBXjoqEg1jC-I2Up4QpPA0Ty4qWm2BDvm_0) [ ![2024-04-253 45 24-ezgif com-video-to-gif-converter](https://private-user-images.githubusercontent.com/77491430/325502379-040e9a9b-6524-423e-b550-f54d308b07e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzE1OTQsIm5iZiI6MTcxNDAzMTI5NCwicGF0aCI6Ii83NzQ5MTQzMC8zMjU1MDIzNzktMDQwZTlhOWItNjUyNC00MjNlLWI1NTAtZjU0ZDMwOGIwN2U0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODM2NDBiMDQyN2MyZDFmMDgyNGJjNmQ4Zjc3ZDNjYzgxNmQ5YTVkYjEzNTk0MGVmMTFhOTkxM2Y2NGYyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.230niwAJTBXjoqEg1jC-I2Up4QpPA0Ty4qWm2BDvm_0) ](https://private-user-images.githubusercontent.com/77491430/325502379-040e9a9b-6524-423e-b550-f54d308b07e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzE1OTQsIm5iZiI6MTcxNDAzMTI5NCwicGF0aCI6Ii83NzQ5MTQzMC8zMjU1MDIzNzktMDQwZTlhOWItNjUyNC00MjNlLWI1NTAtZjU0ZDMwOGIwN2U0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODM2NDBiMDQyN2MyZDFmMDgyNGJjNmQ4Zjc3ZDNjYzgxNmQ5YTVkYjEzNTk0MGVmMTFhOTkxM2Y2NGYyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.230niwAJTBXjoqEg1jC-I2Up4QpPA0Ty4qWm2BDvm_0) [ ](https://private-user-images.githubusercontent.com/77491430/325502379-040e9a9b-6524-423e-b550-f54d308b07e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzE1OTQsIm5iZiI6MTcxNDAzMTI5NCwicGF0aCI6Ii83NzQ5MTQzMC8zMjU1MDIzNzktMDQwZTlhOWItNjUyNC00MjNlLWI1NTAtZjU0ZDMwOGIwN2U0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODM2NDBiMDQyN2MyZDFmMDgyNGJjNmQ4Zjc3ZDNjYzgxNmQ5YTVkYjEzNTk0MGVmMTFhOTkxM2Y2NGYyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.230niwAJTBXjoqEg1jC-I2Up4QpPA0Ty4qWm2BDvm_0)

좋은 생각입니다 :)
