### ISSUE TITLE
메인 랜딩 페이지 서비스 소개 글 작성하기 

### ISSUE THREAD

**Issue by yeona813** [WhatToDo6/WhatToDo#56]
### TODO

- [x] 서비스 소개글 작성

일정을 관리할 뿐만 아니라 팀원을 초대하여 할 일 목록을 공유하고 실시간으로 공유하는 서비스를 제공합니다.
할 일을 다양한 컬럼에 배치하여 프로젝트의 진행 상황을 한 눈에 파악할 수 있습니다!
각 할 일에 대한 담당자, 태그, 마감일 등을 지정하여 세부사항을 관리할 수 있습니다.
효율적인 일정 관리가 가능합니다!

**Comment by innerstella** [comment]
모든 일을 한 곳에서 처리하고 빠르게 작업을 완료하세요.
다양한 태그를 지정하여 업무를 효율적으로 관리해보세요.
댓글을 통해 팀원 간 활발한 피드백을 주고받을 수 있습니다.

**Comment by JaeBeen95** [comment]
Taskify로 일상을 간편하게 관리해 보세요! 일상의 할일을 쉽게 등록하고, 언제 어디서나 진행 상황을 체크할 수 있어, 일정 관리가 한결 편해지고 생산성도 높아집니다!
